### ISSUE TITLE
not compatible with Genshin 3.0

### ISSUE THREAD

**Issue by TheProJeckt** [Ennea/wishing-well#1]
"Could not find authentication token in the log file. Open the wish history in the game, then try again." not compatible with Genshin 3.0

**Comment by Ennea** [comment]
And it won't be, as far as I can tell. Sorry about that, but there's no way to access the required auth token anymore, as it's not being logged in the game's log file anymore. I've yet to take a look at the Android version, it may still easily be available there. As for PC only, I may look into other options such as OCR or just adding wishes manually. Will update this issue once I have more/new info.

**Comment by Ennea** [comment]
So, turns out the URL can still be found, just.. elsewhere. Thanks for paimon.moe's Made Baruna for this one :)
