### ISSUE TITLE
Genshin Impact is not installed or has not been started yet.

### ISSUE THREAD

**Issue by VladlenAoki** [Ennea/wishing-well#3]
I get this message when game is opened on PC.

**Comment by Ennea** [comment]
Right, my error messages aren't as useful anymore after the last round of changes... Have you opened the wish history in the game already? Can you go inside the game folder and check if the file `Genshin Impact game/GenshinImpact_Data/webCaches/Cache/Cache_Data/data_2` exists?

**Comment by VladlenAoki** [comment]
> 

Yes, I've opened wish history. This file exists.

**Comment by Ennea** [comment]
Which version of Windows are you on? If you enter `powershell` into the Win-R dialog, does PowerShell open? Did you manually move Genshin to another folder after installing it?

**Comment by VladlenAoki** [comment]
Windows 10. PowerShell opens. As far as I can tell I did not move Genshin to another folder. Wishing well worked perfectly before 3.0 update.

**Comment by Ennea** [comment]
Yea, sadly with 3.0 I need to grab the auth key for the history from someplace else. Can you open your registry (Win-R -> `regedit`), go to `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\Genshin Impact` and check if the `InstallPath` value actually points to the correct Genshin install path?

**Comment by VladlenAoki** [comment]
I checked this folder and it doesn't contain InstallPath value, only DisplayVersion, UUID and empty one. How to fix it?

**Comment by Ennea** [comment]
You could add it manually. Right click into the view with the values, select `New` -> `String Value` and call it `InstallPath`. Then double click it to edit the value and set it to the full path of the game. For example, in my case, it's set to: `C:\Users\Ennea\Games\Genshin Impact`.

I will also go ahead and update Wishing Well soon-ish to grab the path from elsewhere if pulling it from the registry fails. You could also wait for that :)

**Comment by VladlenAoki** [comment]
It worked! Thank you very much :)

**Comment by Ennea** [comment]
Thank _you_ for helping me diagnose it :)

**Comment by Ennea** [comment]
Closed this one with 1.3.3.
